### ISSUE TITLE
Display mmo/l values?

### ISSUE THREAD

**Issue by zshh** [Rytiggy/api-watchface#16]
Hi,

I've managed to sideload the app to my ionic watch and it seems to work, at least displays values. However they are displayed in mgdl instead of mmol which I would prefer.
I've tried changing the mmol/mgdl switch in the settings menu for the app, but it doesn't seem to make any difference.

Am I doing something wrong or is it not implemented yet?

Thanks in advance

**Comment by Rytiggy** [comment]
I broke the switch from mm/ol to mg/dl in the last update, thanks for making me aware of it 👍. I should have the fix in tonight or tomorrow.

**Comment by Rytiggy** [comment]
@zshh okay if you grab the latest code from master it will support mmol now. To use mmol go into Xdrip/settings/glucose units and change your units to your desired value. changing the value in xdrip will change the value on the watch

https://github.com/Rytiggy/api-watchface/pull/17

**Comment by zshh** [comment]
Excellent, works fine now, thank you :)

ps. The graph it self is still mgdl (200, 175, 150 etc) and also delta is in "X mg/dl", but guess this is low priority for now (just wanted to mention it)

**Comment by Rytiggy** [comment]
Yeah I'm going to be doing quality assurance on the code base soon to fix things like that. I figured I'd do a hotfix to get the mmol working before I go though and do the QA check. I appreciate you pointing out these issues it's super helpful!
