### ISSUE TITLE
Graph doesnt adjust when values go out or range

### ISSUE THREAD

**Issue by danpowell88** [Rytiggy/api-watchface#6]
Had a high today and noticed that the graph doesnt appear to adjust to fit in the new values.

![Imgur](https://i.imgur.com/3J4zBRD.jpg)

**Comment by Rytiggy** [comment]
@danpowell88  Hey got around to implementing this, let me know how it works for you if you get a chance

**Comment by danpowell88** [comment]
Hey sorry I ended up returning my fitbit and going with Garmin, best of luck with the app

**Comment by paleoCoder** [comment]
Just loaded up the latest, I'll test it out.
